package bdrumbo;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import bdrumbo.Usuario;
import bdrumbo.Universidad;
import bdrumbo.Carrera;

import bdrumbo.UsuarioDao;
import bdrumbo.UniversidadDao;
import bdrumbo.CarreraDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig usuarioDaoConfig;
    private final DaoConfig universidadDaoConfig;
    private final DaoConfig carreraDaoConfig;

    private final UsuarioDao usuarioDao;
    private final UniversidadDao universidadDao;
    private final CarreraDao carreraDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        usuarioDaoConfig = daoConfigMap.get(UsuarioDao.class).clone();
        usuarioDaoConfig.initIdentityScope(type);

        universidadDaoConfig = daoConfigMap.get(UniversidadDao.class).clone();
        universidadDaoConfig.initIdentityScope(type);

        carreraDaoConfig = daoConfigMap.get(CarreraDao.class).clone();
        carreraDaoConfig.initIdentityScope(type);

        usuarioDao = new UsuarioDao(usuarioDaoConfig, this);
        universidadDao = new UniversidadDao(universidadDaoConfig, this);
        carreraDao = new CarreraDao(carreraDaoConfig, this);

        registerDao(Usuario.class, usuarioDao);
        registerDao(Universidad.class, universidadDao);
        registerDao(Carrera.class, carreraDao);
    }
    
    public void clear() {
        usuarioDaoConfig.getIdentityScope().clear();
        universidadDaoConfig.getIdentityScope().clear();
        carreraDaoConfig.getIdentityScope().clear();
    }

    public UsuarioDao getUsuarioDao() {
        return usuarioDao;
    }

    public UniversidadDao getUniversidadDao() {
        return universidadDao;
    }

    public CarreraDao getCarreraDao() {
        return carreraDao;
    }

}
